create table if not exists public.ordens_servico (
  id bigint generated by default as identity primary key,
  modelo_aparelho text not null,
  defeito_relatado text not null,
  custo_peca numeric default 0 check (custo_peca >= 0),
  valor_mao_de_obra numeric default 0 check (valor_mao_de_obra >= 0),
  status_os text default 'Em Análise' check (
    status_os in ('Em Análise', 'Aguardando Peça', 'Concluído')
  ),
  created_at timestamp with time zone default now()
);

-- Projeto escolar/demonstração: acesso público proposital para o Snack.
alter table public.ordens_servico disable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.ordens_servico to anon, authenticated;
grant usage, select on sequence public.ordens_servico_id_seq to anon, authenticated;
